language: node_js
node_js: node

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm test
  - npm run build

after success:
  - npm install -g netlify-cli
  - netlify deploy --token "$NETLIFY_TOKEN" 

on:
    branch: master