language: node_js
node_js:
  - "stable"

script:
  - yarn install
  - yarn test
  - yarn run build

deploy:
  provider: netlify
  skip_cleanup: true
  domain: https://timer-application.netlify.app/
  project: ./build/

on:
  branch: master