language: node_js
node_js:
  - "stable"
    
script:
  - npm install
  - npm test
  - npm run build

deploy:
  provider: netlify
  site: https://timer-application.netlify.app/
  edge: true
  dir: ./build/

on:
  branch: master